---
 - hosts: localhost
   connection: local
   become: true
   vars_files:
     - vars/main.yml
   pre_tasks:
     - name: update
       package: update_cache=yes
       changed_when: False

   tasks:
     - include: tasks/packages.yml
     - include: tasks/flatpak.yml
     - include: tasks/configs.yml
