---
 - hosts: localhost
   connection: local
   become: true
   pre_tasks:
     - name: update dnf
       dnf: update_cache=yes
       changed_when: False

   tasks:
     - include: tasks/packages.yml
     - include: tasks/flatpak.yml
     - include: tasks/configs.yml
