- name: is flatpak installed?
  ansible.builtin.stat:
    path: /usr/bin/flatpak
  register: p
- name: Print a debug message
  ansible.builtin.debug:
    msg: "Path exists and is a directory"
  when: p.stat.isdir is defined and p.stat.isdir

- name: Install discord flatpak
  flatpak:
    name: com.discordapp.Discord
    state: present

- name: Install postman flatpak
  flatpak:
    name: com.getpostman.Postman
    state: present

- name: Install slack flatpak
  flatpak:
    name: com.slack.Slack
    state: present

- name: Install Spotify flatpak
  flatpak:
    name: com.slack.Slack
    state: present

- name: Install VSCode flatpak
  flatpak:
    name: com.visualstudio.code
    state: present
